### ISSUE TITLE
What is the point with sub-modules?

### ISSUE THREAD

**Issue by gilbertoca** [AdamBien/javaee-bce-archetype#3]
It is not a issue, but a question: 
- why does it have a empty sub-module?
- shouldn't all the business components reside in the mentioned sub-module?
- there is no standard names in the view sub-module, how would you name packages in it? Control?
  Regards

**Comment by AdamBien** [comment]
This project is just the maven archetype (wizard) which generates the actual project. I think you are actually interested in the [https://github.com/AdamBien/javaee-bce-pom](https://github.com/AdamBien/javaee-bce-pom) project, right?

**Comment by gilbertoca** [comment]
The questions still apply, doesn't it?
